apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://10.18.79.142:8080/root/gitops-manifests.git
  password: G1tl@b-2024-S3cur3-P@ss!
  username: root
