apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-microservice-staging
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  project: default
  source:
    path: overlays/staging
    repoURL: http://10.18.79.142:8080/root/gitops-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
